# Site Settings
title: Animesh's World
email:
description: >
    Welcome to the world of Animesh
baseurl: ""
url: "http://localhost:4000"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM